packages:
  - pkgs/*
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.23.2+sha512-i98PpAQBtCekTHiI7OFquWJj9abxXv5fvfye+JLjs0krwK/9CSGH1gsLdXK6wQPkU20AHUJ4nuQC17ScCmpBaA==
