packages:
  - pkgs/*
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.24.1+sha512-JlfQjiEYQAjdKDg2obndB29rmWVOYEo7A+gwUxprVVjbGsUvbvlNs+e7UGGRhTfkZmgTBHgBWYSXCQSeFMTNwg==
