name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, changeset-release/main]
    types: [opened, synchronize, reopened, edited, closed]
  workflow_dispatch:
    inputs:
      dry_run:
        description: Run in dry-run mode
        type: boolean
        default: true

permissions:
  contents: write
  pull-requests: write
  id-token: write
  packages: write
  attestations: write
  checks: write

jobs:
  release:
    uses: savvy-web/release-dispatcher-action/.github/workflows/release.yml@main
    with:
      dry-run: ${{ inputs.dry_run || false }}
    secrets: inherit
